import type { CausalGraph } from '../types/graph.ts'
import type {
  Debate,
  Theory,
} from '../types/reasoning.ts'



export function makeGraph(overrides: Partial<CausalGraph> = {}): CausalGraph {
  return {
    projectId: 'project-1',
    nodes: [
      {
        id: 'claim-1',
        text: 'Vendor readiness is unconfirmed',
        claimType: 'assumption',
        confidence: 0.6,
        belief: 0.6,
        sensitivity: 0.4,
        isCriticalPath: true,
        isConvergencePoint: false,
        logicGate: 'or',
        orderIndex: 0,
        sourceSentence: null,
        beliefLow: null,
        beliefHigh: null,
        reviewStatus: 'accepted',
        isActive: true,
        userNote: null,
        prior: 0.45,
        corroboratedBy: ['retro-2024.pdf sentence'],
        duplicateCount: 2,
      },
      {
        id: 'claim-2',
        text: 'The delivery schedule slips',
        claimType: 'prediction',
        confidence: 0.55,
        belief: 0.55,
        sensitivity: 0.3,
        isCriticalPath: true,
        isConvergencePoint: false,
        logicGate: 'or',
        orderIndex: 1,
        sourceSentence: null,
        beliefLow: null,
        beliefHigh: null,
        reviewStatus: 'accepted',
        isActive: true,
        userNote: null,
        prior: 0.55,
        corroboratedBy: null,
        duplicateCount: 0,
      },
    ],
    edges: [
      {
        id: 'edge-1',
        sourceId: 'claim-1',
        targetId: 'claim-2',
        mechanism: 'Unconfirmed readiness delays integration',
        strength: 0.8,
        evidenceScore: 0.7,
        sensitivity: 0.5,
        isFeedback: false,
        evidences: [
          {
            id: 'evidence-1',
            evidenceType: 'supporting',
            sourceUrl: 'https://example.org/report',
            sourceTitle: 'Integration delay study',
            snippet: 'Late vendor confirmation correlates with slippage.',
            relevanceScore: 0.8,
            credibilityScore: 0.9,
            sourceTier: 1,
          },
          {
            id: 'evidence-2',
            evidenceType: 'contradicting',
            sourceUrl: 'https://example.org/counter',
            sourceTitle: 'Parallel workstream case study',
            snippet: 'Parallel workstreams absorbed vendor delays.',
            relevanceScore: 0.6,
            credibilityScore: 0.5,
            sourceTier: 3,
          },
        ],
        reviewStatus: 'accepted',
        isActive: true,
        userNote: null,
        strengthOverride: null,
        effectiveStrength: 0.8,
        effect: 0.85,
        linkConfidence: 0.94,
        authorEffect: 0.95,
        authorConfidence: 0.95,
        blindScored: true,
        inflation: 0.1,
      },
    ],
    criticalPath: ['claim-1', 'claim-2'],
    hasTemporal: false,
    graphRevision: 3,
    decisionObjective: null,
    ...overrides,
  } as CausalGraph
}

/** A comparison between two theories. Competing with a usable discriminator. */
export function makeDebate(overrides: Partial<Debate> = {}): Debate {
  return {
    id: 'debate-1',
    theoryAId: 'theory-1',
    theoryBId: 'theory-2',
    overlapJaccard: 0.29,
    relation: 'competing',
    sharedClaimIds: ['claim-1'],
    sharedEdgeIds: ['edge-1'],
    divergentClaimIds: ['claim-2'],
    divergentEdgeIds: ['edge-2', 'edge-3'],
    crux:
      'Both accept the integration window is compressed. A says the vendor ' +
      'cannot deliver into it; B says the team ships but with defects.',
    discriminator:
      "Over 3 weeks watch the vendor's committed dates and the staging defect " +
      'rate. Dates move -> A. Dates hold but defects rise -> B.',
    discriminatorFeasible: true,
    discriminatorHorizonDays: 21,
    evidenceFavours: 'neither',
    bothPossible: false,
    isStale: false,
    promotedTripwireAt: null,
    createdAt: '2026-07-26T00:00:00Z',
    ...overrides,
  }
}

export function makeTheory(overrides: Partial<Theory> = {}): Theory {
  return {
    id: 'theory-1',
    projectId: 'project-1',
    theoryKey: 'key-1',
    title: 'Schedule exposure driven by vendor readiness',
    summary: 'Unconfirmed vendor readiness puts the delivery date at risk.',
    status: 'supported',
    connectedLinks: 1,
    citedLinks: 1,
    causalChain: [
      { claimId: 'claim-1', label: 'Vendor readiness is unconfirmed' },
      {
        edgeId: 'edge-1',
        sourceClaimId: 'claim-1',
        targetClaimId: 'claim-2',
        label: 'Unconfirmed readiness delays integration',
      },
      { claimId: 'claim-2', label: 'The delivery schedule slips' },
    ],
    supportingClaimIds: ['claim-1', 'claim-2'],
    supportingEdgeIds: ['edge-1'],
    supportingEvidenceIds: ['evidence-1'],
    contradictingEvidenceIds: ['evidence-2'],
    weakAssumptions: ['Critical-path exposure has not been confirmed'],
    confidence: 0.72,
    businessImpact: 'high',
    recommendation: 'Confirm vendor readiness before committing to the date.',
    openQuestionIds: [],
    graphRevision: 3,
    theoryRevision: 1,
    version: 1,
    isCurrent: true,
    isStale: false,
    staleReason: null,
    changeKind: 'new',
    changeExplanation: null,
    createdAt: '2026-07-01T00:00:00Z',
    objectionLoad: 0,
    contested: false,
    adjustedScore: 0.72,
    objections: [],
    tripwires: [],
    confidenceBand: 'high',
    outsideViewDelta: null,
    outsideViewNote: null,
    ...overrides,
  }
}
